# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/favicon.ico # (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Kwangyeol Jung's Resume
title: Full Stack Web Developer
email: bluecara82@gmail.com
# email_title: Email (Email title override)
phone: +82-10-88881-2860
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)
address: South Korea
Notice period: 2 Months

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: 
github_username: bluecara
#stackoverflow_username: "00000001"
#dribbble_username: 
#facebook_username: 
#flickr_username: 
instagram_username: kevin_jung__
linkedin_username: kevin-jung-695345163
#xing_username: 
#pinterest_username: 
#youtube_username: 
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/kevin.png #Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Kwangyeol Jung.
  
  Seasoned full stack web developer with over 18+ years of comprehensive experience in software development across various industries.
  Passionate about crafting user-centric solutions that enhance engagement and drive innovation.
  Aiming to leverage extensive technical expertise and a results-oriented approach to contribute to the success of a dynamic team.
  
content:
  - title: Skills
    layout: list
    content:
      - layout: left
        title: Programming Languages
        description: | # this will include new lines to allow paragraphs
          PHP, Python, React, JavaScript, HTML, CSS, etc
      - layout: left
        title: Frameworks & Libraries
        description: | # this will include new lines to allow paragraphs
          Codeigniter, Laravel, jQuery, Bootstrap, etc
      - layout: left
        title: Databases
        description: | # this will include new lines to allow paragraphs
          MariaDB, MySQL, Redis, MongoDB, Oracle, etc
      - layout: left
        title: Tools & Platforms
        description: | # this will include new lines to allow paragraphs
          AWS, Jira, Confluence, Github, Vscode, PhpStorm, MySQL Workbench, Docker, Git, SVN, etc
      - layout: left
        title: Additional Skills
        description: | # this will include new lines to allow paragraphs
          Photoshop, MS Office Suite, Krpano
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Motioneye
        sub_title: PHP Developer (Full Stack)
        caption: Dec 2024 – Present
        link: motioneye.co.kr
        quote: >
          Seoul, South Korea
        description: | # this will include new lines to allow paragraphs
          Spearheaded the stabilization of e-Commerce services, enhancing user experience and reducing downtime.
          
          Led the redevelopment of the **Monomart** application, improving functionality and user engagement.
      - layout: left
        title: THK company
        sub_title: PHP Developer (Full Stack)
        caption: Mar 2024 – Dec 2024
        link: thkc.co.kr
        quote: >
          Seoul, South Korea
        description: | # this will include new lines to allow paragraphs
          Led the development of the nursing information platform, nurse mall service, to promote user engagement and business growth.
          
          Managed the <mark>AWS</mark> systems, optimizing data accessibility and security.
      - layout: left
        title: Dreameut
        sub_title: PHP Developer (Full Stack)
        caption: May 2023 – Oct 2023
        link: dreameut.co.kr
        quote: >
          Seoul, South Korea
        description: | # this will include new lines to allow paragraphs
          Spearheaded the stabilization of e-Commerce services, enhancing user experience and reducing downtime.
          
          Led the redevelopment of the **Monthly Food** application, improving functionality and user engagement.
          
          Successfully integrated a new <mark>Payment Gateway (PG)</mark>, streamlining transaction processes.
          
          Enhanced sales menu design and implemented comprehensive statistics for the integrated system, boosting sales insights.
      - layout: left
        title: Davvero Art
        sub_title: PHP Developer
        caption: Jul 2022 – May 2023
        link: davvero-art.com
        quote: >
          Seoul, South Korea
        description: | # this will include new lines to allow paragraphs
          Pioneered the development and standardization of <mark>WebVR</mark> content, elevating the interactive user experience.
          
          Oversaw website management and back-office development, ensuring seamless operations.
          
          Managed Network Attached Storage (<mark>NAS</mark>) systems, optimizing data accessibility and security.
      - layout: left
        title: Jason Group
        sub_title: PHP Developer (Backend)
        caption: Jul 2020 – May 2022
        link: jasongroup.co.kr
        quote: >
          Seoul, South Korea
        description: | # this will include new lines to allow paragraphs
          Developed a live commerce solution back-office, automating promotion and enhancing sales strategies.
          
          Engineered a search management solution, significantly improving product discoverability and user satisfaction.
      - layout: left
        title: ConnectWave
        sub_title: PHP Developer (Full Stack)
        caption: Nov 2011 – Jun 2020
        link: connectwave.co.kr
        quote: >
          Seoul, South Korea
        description: | # this will include new lines to allow paragraphs
          Led the development of eight innovative services, including chatbots, video commerce platforms, and social content management, driving user engagement and business growth.
          
          Implemented a mobile website for the education team, enhancing accessibility and user experience.
          
          Developed an electronic tax invoice back-office and integrated services with Kakaotalk channel, improving operational efficiency.
      - layout: left
        title: Aisa Business Daily
        sub_title: PHP Developer
        caption: Mar 2011 – Nov 2011
        link: asiae.co.kr
        quote: >
          Seoul, South Korea
        description: | # this will include new lines to allow paragraphs
          Developed multiple web services.
      - layout: left
        title: Pagoda SCS
        sub_title: PHP Developer
        caption: May 2007 – Mar 2011
        link: pagoda21.com
        quote: >
          Seoul, South Korea
        description: | # this will include new lines to allow paragraphs
          Developed educational websites and added B2B convenience features.
      - layout: left
        title: Netpia
        sub_title: PHP Developer
        caption: Dec 2006 – May 2007
        link: netpia.com
        quote: >
          Seoul, South Korea
        description: | # this will include new lines to allow paragraphs
          Participated in the SMS sending program TFT team.
      - layout: left
        title: People Who Enjoy Traveling
        sub_title: PHP Developer
        caption: Dec 2005 – Dec 2006
        quote: >
          Seoul, South Korea
        description: | # this will include new lines to allow paragraphs
          Upgraded the website and built an intranet.
  - title: Education
    layout: list
    content:
      - layout: left
        title: Computer Engineering
        sub_title: Soonchunhyang University
        caption: 2001 – 2007, Chungnam, South Korea
        quote: >
          B.Sc. in Information Technology Engineering (GPA : 3.5/4.5)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
